microblaze: generic: fix missing symbols w/o gpio
Without xilinx gpio driver (systems w/o dedicated gpio controler)
the fdtdec library part will missing symbols: gpio_get_value(),
gpio_set_value(), and gpio_request().

Error is:

  lib/libgeneric.o: In function `fdtdec_get_gpio':
  /u-boot-2013.10/lib/fdtdec.c:506: undefined reference to `gpio_get_value'
  lib/libgeneric.o: In function `fdtdec_set_gpio':
  /u-boot-2013.10/lib/fdtdec.c:516: undefined reference to `gpio_set_value'
  lib/libgeneric.o: In function `fdtdec_setup_gpio':
  /u-boot-2013.10/lib/fdtdec.c:528: undefined reference to `gpio_request'

Signed-off-by: Stephan Linz <linz@li-pro.net>